language: c
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - pkg-config netcdf-bin libnetcdf-dev openmpi-bin libopenmpi-dev gfortran

before_install:
  - test -n $CC && unset CC
  - test -n $FC && unset FC
  - test -n $CPPFLAGS && unset CPPFLAGS
  - test -n FCFLAGS && unset FCFLAGS

before_script:
  - export CC=mpicc
  - export CPPFLAGS='-I/usr/include'

env:
  global:
    - CC=mpicc
    - FC=mpifort
    - CPPFLAGS='-I/usr/include'
    - CFLAGS='-std=c99'
    - LDFLAGS='-L/usr/lib'
  
script:
  - autoreconf -i
  - ./configure
  - make -j distcheck
  - make -j distclean
  - rm -rf build
  - mkdir build
  - cd build
  - cmake -DPIO_HDF5_LOGGING=On -DPIO_USE_MALLOC=On -DPIO_ENABLE_LOGGING=On -DWITH_PNETCDF=Off ..
  - make
 
