#!/bin/bash
#
# This script is for configuring adios on the authors' machines
# You can study it to figure out how to configure adios on your system
#

SRCDIR=`dirname ${BASH_SOURCE[0]}`

if [ `hostname | cut -c 1-4` == "rhea" ]; then
    echo "Configure on Rhea"
    TARGET=`module list 2>&1 | grep "PE"- | sed "s/^.*PE-\([a-z]*\).*/\1/"`
    NETCDF_DIR=/ccs/proj/e2e/pnorbert/netcdf-4.4.0/install/rhea.$TARGET
    PNETCDF_DIR=/ccs/proj/e2e/pnorbert/parallel-netcdf-1.8.1/install/rhea.$TARGET
    CC=mpicc \
    CXX=mpic++ \
    FC=mpif90 \
    CFLAGS="-g -fPIC" \
    ADIOS_DIR=/ccs/proj/csc143/ACME_support/pnorbert/rhea.$TARGET/adios \
    cmake -DNetCDF_C_PATH=$NETCDF_DIR \
          -DNetCDF_Fortran_PATH=$NETCDF_DIR \
          -DPnetCDF_PATH=$PNETCDF_DIR \
          -DCMAKE_INSTALL_PREFIX=/ccs/proj/csc143/ACME_support/rhea.$TARGET/pio \
          ..

elif [ `hostname | cut -c 1-4` == "sith" ]; then
    echo "Configure on Sith"
    TARGET=`module list 2>&1 | grep "PE"- | sed "s/^.*PE-\([a-z]*\).*/\1/"`
    NETCDF_DIR=/ccs/proj/e2e/pnorbert/netcdf-4.4.0/install/rhea.$TARGET
    PNETCDF_DIR=/ccs/proj/csc143/ACME_support/sith.$TARGET/pnetcdf
    CC=mpicc \
    CXX=mpic++ \
    FC=mpif90 \
    CFLAGS="-g -fPIC" \
    ADIOS_DIR=/ccs/proj/csc143/ACME_support/sith.$TARGET/adios \
    cmake -DNetCDF_C_PATH=$NETCDF_DIR \
          -DNetCDF_Fortran_PATH=$NETCDF_DIR \
          -DPnetCDF_PATH=$PNETCDF_DIR \
          -DCMAKE_INSTALL_PREFIX=/ccs/proj/csc143/ACME_support/sith.$TARGET/pio \
          ..

elif [ `hostname | cut -c 1-5` == "titan" ]; then
    TARGET=`module list 2>&1 | grep "PrgEnv"- | sed "s/^.*PrgEnv-\([a-z]*\).*/\1/"`
    echo "Configure on Titan for $TARGET environment"
    module load cray-hdf5-parallel
    module load cray-netcdf-hdf5parallel
    module load cmake3/3.6.1
    PNETCDF_DIR=/ccs/proj/csc143/ACME_support/titan.$TARGET/pnetcdf
    CC=cc  \
    CXX=CC \
    FC=ftn \
    CFLAGS="-g -fPIC" \
    ADIOS_DIR=/ccs/proj/csc143/ACME_support/titan.$TARGET/adios \
    cmake -DNetCDF_C_PATH=$NETCDF_DIR \
          -DNetCDF_Fortran_PATH=$NETCDF_DIR \
          -DPnetCDF_PATH=$PNETCDF_DIR \
          -DCMAKE_INSTALL_PREFIX=/ccs/proj/csc143/ACME_support/titan.$TARGET/pio \
          ..

elif [ `hostname | cut -c 1-7` == "adiosVM" ]; then

    #######################
    # ADIOS Virtual Box #
    #######################
    echo "Configure on ADIOS VirtualBox."
    CC=mpicc \
    CXX=mpic++ \
    FC=mpif90 \
    CFLAGS="-g -fPIC" \
    ADIOS_DIR=/opt/adios/lean \
    cmake -DNetCDF_C_PATH=/opt/netcdf-4.4.0-parallel \
          -DNetCDF_Fortran_PATH=/opt/netcdf-4.4.0-parallel \
          -DPnetCDF_PATH=/opt/pnetcdf-1.8.1 \
          -DCMAKE_INSTALL_PREFIX=/opt/pio \
          ..

else
    echo "Could not determine what machine is this."
    echo "This script is for configuring pio/adios on the authors' machines."
    echo "You can study it to figure out how to configure adios on your system."
fi
    
    
    
