!===================================================
! DO NOT EDIT THIS FILE, it was generated using genf90/src/genf90/genf90.pl 
! Any changes you make to this file may be lost
!===================================================
#define __PIO_FILE__ "pionfatt_mod.F90"
!>
!! @file
!! @brief NetCDF attribute interface to PIO
!<
!>
!!  @defgroup PIO_put_att Write Attributes
!!  Writes an attribute to a file in Fortran.
!<
!>
!! @defgroup PIO_get_att Read Attributes
!! Reads an attribute from a file in Fortran.
!<

module pionfatt_mod
  use pio_kinds, only : r4, r8, i4, pio_offset_kind
  use pio_types
  use pio_support, only : replace_c_null
  use iso_c_binding
  implicit none


  !>
  !! @private
  !<
  public :: put_att
# 27 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  interface put_att
     module procedure put_att_id_text, put_att_desc_text, put_att_vid_text
     module procedure put_att_id_real, put_att_desc_real, put_att_vid_real
     module procedure put_att_id_double, put_att_desc_double, put_att_vid_double
     module procedure put_att_id_int, put_att_desc_int, put_att_vid_int
     ! TYPE real,int,double
     module procedure put_att_1d_id_real
     ! TYPE real,int,double
     module procedure put_att_1d_id_int
     ! TYPE real,int,double
     module procedure put_att_1d_id_double
     ! TYPE real,int,double
     module procedure put_att_1d_desc_real
     ! TYPE real,int,double
     module procedure put_att_1d_desc_int
     ! TYPE real,int,double
     module procedure put_att_1d_desc_double
     ! TYPE real,int,double
     module procedure put_att_1d_vid_real
     ! TYPE real,int,double
     module procedure put_att_1d_vid_int
     ! TYPE real,int,double
     module procedure put_att_1d_vid_double
  end interface


  !>
  !! @private
  !<
  public :: get_att
# 42 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  interface get_att
     module procedure get_att_text, get_att_desc_text, get_att_id_text
     module procedure get_att_real, get_att_desc_real, get_att_id_real
     module procedure get_att_double, get_att_desc_double, get_att_id_double
     module procedure get_att_int, get_att_desc_int, get_att_id_int
     ! TYPE real,int,double
     module procedure get_att_1d_real, get_att_desc_1d_real, get_att_1d_id_real
     ! TYPE real,int,double
     module procedure get_att_1d_int, get_att_desc_1d_int, get_att_1d_id_int
     ! TYPE real,int,double
     module procedure get_att_1d_double, get_att_desc_1d_double, get_att_1d_id_double
  end interface

  !> @cond doxygen_cant_handle_so_exclude
  private :: modName
  character(len=*), parameter :: modName='pionfatt_mod'
# 51 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  interface
# 52 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     integer(C_INT) function PIOc_put_att_text (ncid, varid, name, len, op) &
          bind(C,name="PIOc_put_att_text")
       use iso_c_binding
       integer(C_INT), value    :: ncid
       integer(C_INT), value    :: varid
       character(C_CHAR)        :: name(*)
       integer(C_SIZE_T), value :: len
       character(C_char)        :: op
# 60 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     end function PIOc_put_att_text
  end interface
# 62 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  interface
# 63 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     integer(C_INT) function PIOc_get_att_text (ncid, varid, name, op) &
          bind(C,name="PIOc_get_att_text")
       use iso_c_binding
       integer(C_INT), value    :: ncid
       integer(C_INT), value    :: varid
       character(C_CHAR)        :: name(*)
       character(C_char)        :: op(*)
# 70 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     end function PIOc_get_att_text
  end interface


# 74 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  interface
# 75 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     integer(C_INT) function PIOc_put_att_int (ncid, varid, name, xtype, len, op) &
          bind(C,name="PIOc_put_att_int")
       use iso_c_binding
       integer(C_INT), value    :: ncid
       integer(C_INT), value    :: varid
       character(C_CHAR)        :: name(*)
       integer(C_INT), value    :: xtype
       integer(C_SIZE_T), value :: len
       integer(C_INT)           :: op
# 84 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     end function PIOc_put_att_int
  end interface
# 86 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  interface
# 87 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     integer(C_INT) function PIOc_put_att_float (ncid, varid, name, xtype, len, op) &
          bind(C,name="PIOc_put_att_float")
       use iso_c_binding
       integer(C_INT), value    :: ncid
       integer(C_INT), value    :: varid
       character(C_CHAR)        :: name(*)
       integer(C_INT), value    :: xtype
       integer(C_SIZE_T), value :: len
       real(C_FLOAT)            :: op
# 96 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     end function PIOc_put_att_float
  end interface
# 98 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  interface
# 99 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     integer(C_INT) function PIOc_put_att_double (ncid, varid, name, xtype, len, op) &
          bind(C,name="PIOc_put_att_double")
       use iso_c_binding
       integer(C_INT), value    :: ncid
       integer(C_INT), value    :: varid
       character(C_CHAR)        :: name(*)
       integer(C_INT), value    :: xtype
       integer(C_SIZE_T), value :: len
       real(C_DOUBLE)           :: op
# 108 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     end function PIOc_put_att_double
  end interface


# 112 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  interface
# 113 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     integer(C_INT) function PIOc_get_att_int (ncid, varid, name, op) &
          bind(C,name="PIOc_get_att_int")
       use iso_c_binding
       integer(C_INT), value         :: ncid
       integer(C_INT), value         :: varid
       character(C_CHAR)             :: name(*)
       integer(C_INT), intent(out)   :: op
# 120 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     end function PIOc_get_att_int
  end interface

# 123 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  interface
# 124 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     integer(C_INT) function PIOc_get_att_float (ncid, varid, name, op) &
          bind(C,name="PIOc_get_att_float")
       use iso_c_binding
       integer(C_INT), value         :: ncid
       integer(C_INT), value         :: varid
       character(C_CHAR)             :: name(*)
       real(C_FLOAT), intent(out) :: op
# 131 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     end function PIOc_get_att_float
  end interface

# 134 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  interface
# 135 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     integer(C_INT) function PIOc_get_att_double (ncid, varid, name, op) &
          bind(C,name="PIOc_get_att_double")
       use iso_c_binding
       integer(C_INT), value         :: ncid
       integer(C_INT), value         :: varid
       character(C_CHAR)             :: name(*)
       real(C_DOUBLE), intent(out)   :: op
# 142 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
     end function PIOc_get_att_double
  end interface
  !> @endcond

# 146 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
contains

  !>
  !! @public
  !! @ingroup PIO_put_att
  !! @brief Writes an netcdf attribute to a file
  !! @details
  !! @param File @copydoc file_desc_t
  !! @param vdesc : The netcdf variable descriptor
  !! @param name : name of the attribute to add
  !! @param values : The value for the netcdf attribute
  !! @retval ierr @copydoc error_return
  !<
# 159 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_desc_text (File, vdesc, name, values) result(ierr)
    type (File_desc_t), intent(in) :: File
    type(var_desc_t), intent(in)  :: vdesc
    character(len=*), intent(in)  :: name
    character(len=*), intent(in) :: values

    ierr = put_att_id_text (File%fh,vdesc%varid,name,values)

# 167 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_desc_text
# 159 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_desc_real (File, vdesc, name, values) result(ierr)
    type (File_desc_t), intent(in) :: File
    type(var_desc_t), intent(in)  :: vdesc
    character(len=*), intent(in)  :: name
    real(r4), intent(in) :: values

    ierr = put_att_id_real (File%fh,vdesc%varid,name,values)

# 167 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_desc_real
# 159 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_desc_double (File, vdesc, name, values) result(ierr)
    type (File_desc_t), intent(in) :: File
    type(var_desc_t), intent(in)  :: vdesc
    character(len=*), intent(in)  :: name
    real(r8), intent(in) :: values

    ierr = put_att_id_double (File%fh,vdesc%varid,name,values)

# 167 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_desc_double
# 159 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_desc_int (File, vdesc, name, values) result(ierr)
    type (File_desc_t), intent(in) :: File
    type(var_desc_t), intent(in)  :: vdesc
    character(len=*), intent(in)  :: name
    integer(i4), intent(in) :: values

    ierr = put_att_id_int (File%fh,vdesc%varid,name,values)

# 167 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_desc_int
# 168 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_vid_text (File, varid, name, value) result(ierr)
    type (File_desc_t), intent(in) :: File
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    character(len=*), intent(in) :: value

    ierr = put_att_id_text (File%fh,varid,name,value)

# 176 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_vid_text
# 168 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_vid_real (File, varid, name, value) result(ierr)
    type (File_desc_t), intent(in) :: File
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    real(r4), intent(in) :: value

    ierr = put_att_id_real (File%fh,varid,name,value)

# 176 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_vid_real
# 168 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_vid_double (File, varid, name, value) result(ierr)
    type (File_desc_t), intent(in) :: File
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    real(r8), intent(in) :: value

    ierr = put_att_id_double (File%fh,varid,name,value)

# 176 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_vid_double
# 168 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_vid_int (File, varid, name, value) result(ierr)
    type (File_desc_t), intent(in) :: File
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    integer(i4), intent(in) :: value

    ierr = put_att_id_int (File%fh,varid,name,value)

# 176 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_vid_int
  ! TYPE int,real,double
# 178 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_id_int (ncid, varid, name, values) result(ierr)
    use iso_c_binding
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    integer(i4), intent(in) :: values


    ierr = PIOc_put_att_int (ncid,varid-1,trim(name)//C_NULL_CHAR, PIO_int, 1_C_SIZE_T, values)

# 188 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_id_int
  ! TYPE int,real,double
# 178 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_id_real (ncid, varid, name, values) result(ierr)
    use iso_c_binding
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    real(r4), intent(in) :: values


    ierr = PIOc_put_att_float (ncid,varid-1,trim(name)//C_NULL_CHAR, PIO_real, 1_C_SIZE_T, values)

# 188 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_id_real
  ! TYPE int,real,double
# 178 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_id_double (ncid, varid, name, values) result(ierr)
    use iso_c_binding
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    real(r8), intent(in) :: values


    ierr = PIOc_put_att_double (ncid,varid-1,trim(name)//C_NULL_CHAR, PIO_double, 1_C_SIZE_T, values)

# 188 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_id_double
# 189 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_id_text (ncid, varid, name, values) result(ierr)
    use iso_c_binding
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    character(len=*), intent(in) :: values
    character(c_char), allocatable :: cvar(:)
    integer(C_SIZE_T) :: clen
    integer :: i

    clen = len_trim(values)
    allocate(cvar(clen+1))
    cvar = C_NULL_CHAR
    do i=1,int(clen)
       cvar(i) = values(i:i)
    end do
    ierr = PIOc_put_att_text (ncid,varid-1,trim(name)//C_NULL_CHAR, clen, cvar(1))
    deallocate(cvar)
# 207 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_id_text

# 209 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_1d_id_text (ncid, varid, name, value) result(ierr)
    use iso_c_binding
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    character(len=*), intent(in) :: value(:)
    character, allocatable :: nvalue(:)
    integer :: slen, alen, i, j, k

    slen = len(value(1))
    alen = size(value)
    allocate(nvalue(slen*alen))

    do i=1,alen
       j= len_trim(value(i))
       do k=1,j
          nvalue(k+(i-1)*slen) = value(i)(k:k)
       end do
       nvalue(j+1+(i-1)*slen) = C_NULL_CHAR
    end do
    ierr =  put_att_1d_id_text_internal (ncid, varid, name, slen*alen, nvalue)

    deallocate(nvalue)

# 233 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_1d_id_text


# 236 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_1d_id_text_internal (ncid, varid, name, arrlen, values) result(ierr)
    use iso_c_binding
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    integer, intent(in) :: arrlen
    character(len=*), intent(in) :: values(arrlen)


    ierr = PIOc_put_att_text (ncid,varid-1,trim(name)//C_NULL_CHAR, int(arrlen,C_SIZE_T),values(1))


# 248 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_1d_id_text_internal



# 252 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_id_text (ncid, varid, name, values) result(ierr)
    use iso_c_binding
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    character(len=*), intent(out) :: values

    values = ' '
    ierr = PIOc_get_att_text (ncid,varid-1,trim(name)//C_NULL_CHAR, values)
    call replace_c_null(values)
# 262 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_id_text

  ! TYPE real,double,int
  !>
  !! @public
  !! @ingroup PIO_put_att
  !! @brief Writes an netcdf attribute to a file
  !! @details
  !! @param ncid @copydoc file_desc_t
  !! @param varid : The netcdf variable identifier
  !! @param name : name of the attribute to add
  !! @param values : The value for the netcdf attribute
  !! @retval ierr @copydoc error_return
  !<
# 277 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_1d_id_real (ncid, varid, name, values) result(ierr)
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    real(r4), intent(in) :: values(:)
    integer(PIO_OFFSET_KIND) :: len

    len = size(values)
    ierr = put_att_1d_id_internal_real (ncid, varid, name, len, values)

# 287 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_1d_id_real
  ! TYPE real,double,int
  !>
  !! @public
  !! @ingroup PIO_put_att
  !! @brief Writes an netcdf attribute to a file
  !! @details
  !! @param ncid @copydoc file_desc_t
  !! @param varid : The netcdf variable identifier
  !! @param name : name of the attribute to add
  !! @param values : The value for the netcdf attribute
  !! @retval ierr @copydoc error_return
  !<
# 277 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_1d_id_double (ncid, varid, name, values) result(ierr)
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    real(r8), intent(in) :: values(:)
    integer(PIO_OFFSET_KIND) :: len

    len = size(values)
    ierr = put_att_1d_id_internal_double (ncid, varid, name, len, values)

# 287 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_1d_id_double
  ! TYPE real,double,int
  !>
  !! @public
  !! @ingroup PIO_put_att
  !! @brief Writes an netcdf attribute to a file
  !! @details
  !! @param ncid @copydoc file_desc_t
  !! @param varid : The netcdf variable identifier
  !! @param name : name of the attribute to add
  !! @param values : The value for the netcdf attribute
  !! @retval ierr @copydoc error_return
  !<
# 277 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_1d_id_int (ncid, varid, name, values) result(ierr)
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    integer(i4), intent(in) :: values(:)
    integer(PIO_OFFSET_KIND) :: len

    len = size(values)
    ierr = put_att_1d_id_internal_int (ncid, varid, name, len, values)

# 287 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_1d_id_int

  ! TYPE real,double,int
# 290 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_1d_id_internal_real (ncid, varid, name, len, values) result(ierr)
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    integer(PIO_OFFSET_KIND), intent(in) :: len
    character(len=*), intent(in) :: name
    real(r4), intent(in), target :: values(*)


    ierr = PIOc_put_att_float (ncid, varid-1, trim(name)//C_NULL_CHAR, PIO_real , len, values(1))

# 300 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_1d_id_internal_real
  ! TYPE real,double,int
# 290 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_1d_id_internal_double (ncid, varid, name, len, values) result(ierr)
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    integer(PIO_OFFSET_KIND), intent(in) :: len
    character(len=*), intent(in) :: name
    real(r8), intent(in), target :: values(*)


    ierr = PIOc_put_att_double (ncid, varid-1, trim(name)//C_NULL_CHAR, PIO_double , len, values(1))

# 300 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_1d_id_internal_double
  ! TYPE real,double,int
# 290 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_1d_id_internal_int (ncid, varid, name, len, values) result(ierr)
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    integer(PIO_OFFSET_KIND), intent(in) :: len
    character(len=*), intent(in) :: name
    integer(i4), intent(in), target :: values(*)


    ierr = PIOc_put_att_int (ncid, varid-1, trim(name)//C_NULL_CHAR, PIO_int , len, values(1))

# 300 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_1d_id_internal_int


  ! TYPE real,int,double
  !>
  !! @public
  !! @ingroup PIO_put_att
  !! @brief Writes an netcdf attribute to a file
  !! @details
  !! @param File @copydoc file_desc_t
  !! @param varDesc @copydoc var_desc_t
  !! @param name : name of the attribute to add
  !! @param values : The value for the netcdf attribute
  !! @retval ierr @copydoc error_return
  !<
# 315 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_1d_desc_real (File,varDesc,name,values) result(ierr)

    type (File_desc_t), intent(inout) , target :: File
    type (VAR_desc_t), intent(in)     :: varDesc
    character(len=*), intent(in)      :: name
    real(r4), intent(in)      :: values(:)

    ierr = put_att_1d_id_real (File%fh,varDesc%varid,name,values)

# 324 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_1d_desc_real
  ! TYPE real,int,double
  !>
  !! @public
  !! @ingroup PIO_put_att
  !! @brief Writes an netcdf attribute to a file
  !! @details
  !! @param File @copydoc file_desc_t
  !! @param varDesc @copydoc var_desc_t
  !! @param name : name of the attribute to add
  !! @param values : The value for the netcdf attribute
  !! @retval ierr @copydoc error_return
  !<
# 315 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_1d_desc_int (File,varDesc,name,values) result(ierr)

    type (File_desc_t), intent(inout) , target :: File
    type (VAR_desc_t), intent(in)     :: varDesc
    character(len=*), intent(in)      :: name
    integer(i4), intent(in)      :: values(:)

    ierr = put_att_1d_id_int (File%fh,varDesc%varid,name,values)

# 324 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_1d_desc_int
  ! TYPE real,int,double
  !>
  !! @public
  !! @ingroup PIO_put_att
  !! @brief Writes an netcdf attribute to a file
  !! @details
  !! @param File @copydoc file_desc_t
  !! @param varDesc @copydoc var_desc_t
  !! @param name : name of the attribute to add
  !! @param values : The value for the netcdf attribute
  !! @retval ierr @copydoc error_return
  !<
# 315 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_1d_desc_double (File,varDesc,name,values) result(ierr)

    type (File_desc_t), intent(inout) , target :: File
    type (VAR_desc_t), intent(in)     :: varDesc
    character(len=*), intent(in)      :: name
    real(r8), intent(in)      :: values(:)

    ierr = put_att_1d_id_double (File%fh,varDesc%varid,name,values)

# 324 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_1d_desc_double

# 326 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_1d_vid_text (File,varid,name,value) result(ierr)

    type (File_desc_t), intent(inout) , target :: File
    integer, intent(in) :: varid
    character(len=*), intent(in)      :: name
    character(len=*), intent(in)      :: value(:)

    ierr = put_att_1d_id_text (File%fh,varid,name,value)

# 335 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_1d_vid_text
# 326 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_1d_vid_real (File,varid,name,value) result(ierr)

    type (File_desc_t), intent(inout) , target :: File
    integer, intent(in) :: varid
    character(len=*), intent(in)      :: name
    real(r4), intent(in)      :: value(:)

    ierr = put_att_1d_id_real (File%fh,varid,name,value)

# 335 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_1d_vid_real
# 326 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_1d_vid_double (File,varid,name,value) result(ierr)

    type (File_desc_t), intent(inout) , target :: File
    integer, intent(in) :: varid
    character(len=*), intent(in)      :: name
    real(r8), intent(in)      :: value(:)

    ierr = put_att_1d_id_double (File%fh,varid,name,value)

# 335 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_1d_vid_double
# 326 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function put_att_1d_vid_int (File,varid,name,value) result(ierr)

    type (File_desc_t), intent(inout) , target :: File
    integer, intent(in) :: varid
    character(len=*), intent(in)      :: name
    integer(i4), intent(in)      :: value(:)

    ierr = put_att_1d_id_int (File%fh,varid,name,value)

# 335 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function put_att_1d_vid_int

  !>
  !! @public
  !! @ingroup PIO_get_att
  !! @brief Reads an netcdf attribute from a  file
  !! @details
  !! @param File @copydoc file_desc_t
  !! @param varDesc @copydoc var_desc_t
  !! @param name : name of the attribute to get
  !! @param values : The value for the netcdf attribute
  !! @retval ierr @copydoc error_return
  !<
# 348 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_desc_text (File,varDesc,name,values) result(ierr)

    type (File_desc_t), intent(inout) , target :: File
    type (VAR_desc_t), intent(in)     :: varDesc
    character(len=*), intent(in)      :: name
    character(len=*), intent(out)      :: values

    ierr = get_att_text (File,varDesc%varid,name,values)

# 357 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_desc_text
# 348 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_desc_real (File,varDesc,name,values) result(ierr)

    type (File_desc_t), intent(inout) , target :: File
    type (VAR_desc_t), intent(in)     :: varDesc
    character(len=*), intent(in)      :: name
    real(r4), intent(out)      :: values

    ierr = get_att_real (File,varDesc%varid,name,values)

# 357 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_desc_real
# 348 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_desc_double (File,varDesc,name,values) result(ierr)

    type (File_desc_t), intent(inout) , target :: File
    type (VAR_desc_t), intent(in)     :: varDesc
    character(len=*), intent(in)      :: name
    real(r8), intent(out)      :: values

    ierr = get_att_double (File,varDesc%varid,name,values)

# 357 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_desc_double
# 348 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_desc_int (File,varDesc,name,values) result(ierr)

    type (File_desc_t), intent(inout) , target :: File
    type (VAR_desc_t), intent(in)     :: varDesc
    character(len=*), intent(in)      :: name
    integer(i4), intent(out)      :: values

    ierr = get_att_int (File,varDesc%varid,name,values)

# 357 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_desc_int

  !>
  !! @public
  !! @ingroup PIO_get_att
  !! @brief Reads an netcdf attribute from a  file
  !! @details
  !! @param File @copydoc file_desc_t
  !! @param varDesc @copydoc var_desc_t
  !! @param name : name of the attribute to get
  !! @param values : The value for the netcdf attribute
  !! @retval ierr @copydoc error_return
  !<
  ! TYPE int,real,double
# 371 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_desc_1d_int (File,varDesc,name,values) result(ierr)

    type (File_desc_t), intent(inout) , target :: File
    type (VAR_desc_t), intent(in)     :: varDesc
    character(len=*), intent(in)      :: name
    integer(i4), intent(out)      :: values(:)

    character(len=*), parameter :: subName=modName//'::get_att_desc_1d_int'

    ierr = get_att_1d_id_int (File%fh,varDesc%varid,name,values)

# 382 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_desc_1d_int
  ! TYPE int,real,double
# 371 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_desc_1d_real (File,varDesc,name,values) result(ierr)

    type (File_desc_t), intent(inout) , target :: File
    type (VAR_desc_t), intent(in)     :: varDesc
    character(len=*), intent(in)      :: name
    real(r4), intent(out)      :: values(:)

    character(len=*), parameter :: subName=modName//'::get_att_desc_1d_real'

    ierr = get_att_1d_id_real (File%fh,varDesc%varid,name,values)

# 382 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_desc_1d_real
  ! TYPE int,real,double
# 371 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_desc_1d_double (File,varDesc,name,values) result(ierr)

    type (File_desc_t), intent(inout) , target :: File
    type (VAR_desc_t), intent(in)     :: varDesc
    character(len=*), intent(in)      :: name
    real(r8), intent(out)      :: values(:)

    character(len=*), parameter :: subName=modName//'::get_att_desc_1d_double'

    ierr = get_att_1d_id_double (File%fh,varDesc%varid,name,values)

# 382 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_desc_1d_double

  !>
  !! @public
  !! @ingroup PIO_get_att
  !! @brief Reads an netcdf attribute from a  file
  !! @details
  !! @param ncid : The netcdf file ID
  !! @param varid : The netcdf variable identifier
  !! @param name : name of the attribute to get
  !! @param values : The value for the netcdf attribute
  !! @retval ierr @copydoc error_return
  !<
  ! TYPE int,real,double
# 396 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_id_int (ncid, varid, name, values) result(ierr)
    use iso_c_binding
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    integer(i4), intent(out), target :: values


    ierr = PIOc_get_att_int (ncid,varid-1,trim(name)//C_NULL_CHAR, values)

# 406 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_id_int
  ! TYPE int,real,double
# 396 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_id_real (ncid, varid, name, values) result(ierr)
    use iso_c_binding
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    real(r4), intent(out), target :: values


    ierr = PIOc_get_att_float (ncid,varid-1,trim(name)//C_NULL_CHAR, values)

# 406 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_id_real
  ! TYPE int,real,double
# 396 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_id_double (ncid, varid, name, values) result(ierr)
    use iso_c_binding
    integer, intent(in) :: ncid
    integer, intent(in) :: varid
    character(len=*), intent(in) :: name
    real(r8), intent(out), target :: values


    ierr = PIOc_get_att_double (ncid,varid-1,trim(name)//C_NULL_CHAR, values)

# 406 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_id_double



# 410 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_text (File,varid,name,values) result(ierr)
    type (File_desc_t), intent(in) , target :: File
    integer(i4), intent(in)        :: varid
    character(len=*), intent(in)   :: name
    character(len=*), intent(out)          :: values


    ierr = get_att_id_text (file%fh, varid, name, values)


# 420 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_text
# 410 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_real (File,varid,name,values) result(ierr)
    type (File_desc_t), intent(in) , target :: File
    integer(i4), intent(in)        :: varid
    character(len=*), intent(in)   :: name
    real(r4), intent(out)          :: values


    ierr = get_att_id_real (file%fh, varid, name, values)


# 420 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_real
# 410 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_double (File,varid,name,values) result(ierr)
    type (File_desc_t), intent(in) , target :: File
    integer(i4), intent(in)        :: varid
    character(len=*), intent(in)   :: name
    real(r8), intent(out)          :: values


    ierr = get_att_id_double (file%fh, varid, name, values)


# 420 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_double
# 410 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_int (File,varid,name,values) result(ierr)
    type (File_desc_t), intent(in) , target :: File
    integer(i4), intent(in)        :: varid
    character(len=*), intent(in)   :: name
    integer(i4), intent(out)          :: values


    ierr = get_att_id_int (file%fh, varid, name, values)


# 420 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_int

  ! TYPE real,int,double
  !>
  !! @public
  !! @ingroup PIO_get_att
  !! @brief Reads an netcdf attribute from a  file
  !! @details
  !! @param File @copydoc file_desc_t
  !! @param varid : The netcdf variable identifier
  !! @param name : name of the attribute to get
  !! @param values : The value for the netcdf attribute
  !! @retval ierr @copydoc error_return
  !<
# 434 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_1d_real (File,varid,name,values) result(ierr)
    type (File_desc_t), intent(in) , target :: File
    integer(i4), intent(in)        :: varid
    character(len=*), intent(in)   :: name
    real(r4), intent(out)          :: values(:)

    ierr = get_att_1d_id_real (file%fh, varid, name, values)

# 442 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_1d_real
  ! TYPE real,int,double
  !>
  !! @public
  !! @ingroup PIO_get_att
  !! @brief Reads an netcdf attribute from a  file
  !! @details
  !! @param File @copydoc file_desc_t
  !! @param varid : The netcdf variable identifier
  !! @param name : name of the attribute to get
  !! @param values : The value for the netcdf attribute
  !! @retval ierr @copydoc error_return
  !<
# 434 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_1d_int (File,varid,name,values) result(ierr)
    type (File_desc_t), intent(in) , target :: File
    integer(i4), intent(in)        :: varid
    character(len=*), intent(in)   :: name
    integer(i4), intent(out)          :: values(:)

    ierr = get_att_1d_id_int (file%fh, varid, name, values)

# 442 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_1d_int
  ! TYPE real,int,double
  !>
  !! @public
  !! @ingroup PIO_get_att
  !! @brief Reads an netcdf attribute from a  file
  !! @details
  !! @param File @copydoc file_desc_t
  !! @param varid : The netcdf variable identifier
  !! @param name : name of the attribute to get
  !! @param values : The value for the netcdf attribute
  !! @retval ierr @copydoc error_return
  !<
# 434 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_1d_double (File,varid,name,values) result(ierr)
    type (File_desc_t), intent(in) , target :: File
    integer(i4), intent(in)        :: varid
    character(len=*), intent(in)   :: name
    real(r8), intent(out)          :: values(:)

    ierr = get_att_1d_id_double (file%fh, varid, name, values)

# 442 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_1d_double


  ! TYPE real,int,double
# 446 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_1d_id_real (ncid,varid,name,values) result(ierr)
    integer, intent(in) :: ncid
    integer(i4), intent(in)        :: varid
    character(len=*), intent(in)   :: name
    real(r4), intent(out) , target         :: values(*)

    ierr = PIOc_get_att_float (ncid, varid-1, trim(name)//C_NULL_CHAR, values(1))


# 455 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_1d_id_real
  ! TYPE real,int,double
# 446 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_1d_id_int (ncid,varid,name,values) result(ierr)
    integer, intent(in) :: ncid
    integer(i4), intent(in)        :: varid
    character(len=*), intent(in)   :: name
    integer(i4), intent(out) , target         :: values(*)

    ierr = PIOc_get_att_int (ncid, varid-1, trim(name)//C_NULL_CHAR, values(1))


# 455 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_1d_id_int
  ! TYPE real,int,double
# 446 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  integer function get_att_1d_id_double (ncid,varid,name,values) result(ierr)
    integer, intent(in) :: ncid
    integer(i4), intent(in)        :: varid
    character(len=*), intent(in)   :: name
    real(r8), intent(out) , target         :: values(*)

    ierr = PIOc_get_att_double (ncid, varid-1, trim(name)//C_NULL_CHAR, values(1))


# 455 "/glade/work/haiyingx/ParallelIO_cz5/src/flib/pionfatt_mod.F90.in"
  end function get_att_1d_id_double


end module pionfatt_mod
