name: autotools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CC: mpicc
      FC: mpifort
      CPPFLAGS: "-I/usr/include -I/usr/local/include"
#      CFLAGS: "-std=c99  -fsanitize=address -fno-omit-frame-pointer -Werror"
#      FFLAGS: "-fsanitize=address -fno-omit-frame-pointer"
#      FCFLAGS: "-fsanitize=address -fno-omit-frame-pointer -Werror"

    steps:
    - uses: actions/checkout@v2
    - name: Installs
      run: |
        sudo apt-get install netcdf-bin libnetcdf-dev doxygen graphviz wget gfortran libjpeg-dev libz-dev openmpi-bin libopenmpi-dev 

    - name: Cache pnetcdf
      id: cache-pnetcdf
      uses: actions/cache@v2
      with:
        path: /usr/pnetcdf
        key: ${{ runner.os }}-pnetcdf-1.11.0
    - name: pnetcdf build
      if: steps.cache-pnetcdf.outputs.cache-hit != 'true'
      run: |
        wget https://parallel-netcdf.github.io/Release/pnetcdf-1.11.0.tar.gz 
        tar -xzvf pnetcdf-1.11.0.tar.gz
        ls -l
        pushd pnetcdf-1.11.0
        ./configure --prefix=/usr/pnetcdf --enable-shared --disable-cxx
        make
        sudo make install
        popd

    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: |
        ls -l /usr/pnetcdf
        ls -l /usr/pnetcdf/lib
        export CPPFLAGS="-I/usr/include -I/usr/local/include -I/usr/pnetcdf/include"
        export LDFLAGS="-L/usr/pnetcdf/lib"
        echo $LDFLAGS
        ./configure --enable-fortran --enable-docs --enable-logging
    - name: make check
      run: make -j check
