name: autotools_ubuntu_latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CC: mpicc
      FC: mpifort
      CPPFLAGS: "-I/usr/include -I/usr/local/include -I/home/runner/pnetcdf/include"
      LDFLAGS: "-L/home/runner/pnetcdf/lib"
      PNETCDF_VERSION: 1.12.3
    steps:
    - uses: actions/checkout@v2
    - name: Installs
      run: |
        set -x
        sudo gem install apt-spy2
        sudo apt-spy2 check
        sudo apt-spy2 fix --commit
        # after selecting a specific mirror, we need to run 'apt-get update'
        sudo apt-get update
        sudo apt-get install netcdf-bin libnetcdf-dev doxygen graphviz wget gfortran libjpeg-dev libz-dev openmpi-bin libopenmpi-dev
    - name: cache-pnetcdf
      id: cache-pnetcdf
      uses: actions/cache@v2
      with:
        path: ~/pnetcdf
        key: pnetcdf-${{ runner.os }}-${{ env.PNETCDF_VERSION }}

    - name: build-pnetcdf
      if: steps.cache-pnetcdf.outputs.cache-hit != 'true'
      run: |
        set -x
        wget https://parallel-netcdf.github.io/Release/pnetcdf-${{ env.PNETCDF_VERSION }}.tar.gz &> /dev/null
        tar -xzvf pnetcdf-${{ env.PNETCDF_VERSION }}.tar.gz
        pushd pnetcdf-${{ env.PNETCDF_VERSION }}
        ./configure --prefix=/home/runner/pnetcdf --enable-shared --disable-cxx
        make
        sudo make install
        popd

    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure --enable-fortran  --with-mpiexec='mpiexec --oversubscribe'
    - name: make check
      run: make -j check
