name: autotools ubuntu latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CC: mpicc
      FC: mpifort
      CPPFLAGS: "-I/usr/include -I/usr/lib/x86_64-linux-gnu/netcdf/mpi/include/ "
      LDFLAGS: "-L/usr/lib/x86_64-linux-gnu -lnetcdf_mpi -lpnetcdf"
      PNETCDF_VERSION: checkpoint.1.12.3
      FCFLAGS: "-fallow-argument-mismatch"
    steps:
    - uses: actions/checkout@v3
    - name: Installs
      run: |
        set -x
        sudo apt-get update 
        sudo apt-get install netcdf-bin 
        sudo apt-get install libnetcdf-mpi-19
        sudo apt-get install libnetcdf-mpi-dev
        sudo apt-get install pnetcdf-bin
        sudo apt-get install libpnetcdf-dev
        sudo apt-get install doxygen
        sudo apt-get install graphviz
        sudo apt-get install wget
        sudo apt-get install gfortran
        sudo apt-get install libjpeg-dev
        sudo apt-get install libz-dev
        sudo apt-get install openmpi-bin
        sudo apt-get install libopenmpi-dev
        cd /usr/lib/x86_64-linux-gnu
        sudo ln -fs libnetcdf_mpi.so libnetcdf.so
    - name: Build ParallelIO with autotools
      uses: ./.github/actions/parallelio_autotools
      with:
        enable_fortran: True
        with_mpiexec: 'mpiexec --oversubscribe'
        parallelio_version: ${{ env.GITHUB_SHA }}
    - name: make check
      run: |
        cd $GITHUB_WORKSPACE/parallelio-src   
        make -j check

    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
