name: autotools_ubuntu_latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CC: mpicc
      FC: mpifort
      CPPFLAGS: "-I/usr/include -I/usr/local/include -I/home/runner/pnetcdf/include"
      LDFLAGS: "-L/home/runner/pnetcdf/lib"
      PNETCDF_VERSION: checkpoint.1.12.3
      FCFLAGS: "-fallow-argument-mismatch"
    steps:
    - uses: actions/checkout@v3
    - name: Installs
      run: |
        set -x
        #        sudo gem install apt-spy2
        #        sudo apt-spy2 check
        #        sudo apt-spy2 fix --commit
        # after selecting a specific mirror, we need to run 'apt-get update'
        sudo apt-get update 
        sudo apt-get install netcdf-bin 
        sudo apt-get install libnetcdf-dev
        sudo apt-get install doxygen
        sudo apt-get install graphviz
        sudo apt-get install wget
        sudo apt-get install gfortran
        sudo apt-get install libjpeg-dev
        sudo apt-get install libz-dev
        sudo apt-get install openmpi-bin
        sudo apt-get install libopenmpi-dev
    - name: cache-pnetcdf
      id: cache-pnetcdf
      uses: actions/cache@v3
      with:
        path: ~/pnetcdf
        key: pnetcdf-${{ runner.os }}-${{ env.PNETCDF_VERSION }}
    - name: Build PNetCDF
      if: steps.cache-pnetcdf.outputs.cache-hit != 'true'
      uses: ESCOMP/CDEPS/.github/actions/buildpnetcdf@e06246b560d3132170bb1a5443fa3d65dfbd2040
      with:
        pnetcdf_version: ${{ env.PNETCDF_VERSION }}
        install_prefix: $HOME/pnetcdf
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure --enable-fortran  --with-mpiexec='mpiexec --oversubscribe'
      #run: ./configure --enable-fortran --enable-docs  --with-mpiexec='mpiexec --oversubscribe'
    - name: make check
      run: make -j check
