name: cmake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CC: mpicc
      FC: mpifort
#      CPPFLAGS: "-I/usr/include -I/usr/local/include "
#      LDFLAGS: "-L/usr/lib/x86_64-linux-gnu  -lnetcdf -lpnetcdf"
      FCFLAGS: "-fallow-argument-mismatch"
    steps:
    - uses: actions/checkout@v3
    - name: Installs
      run: |
        set -x
        sudo apt-get update
        sudo apt-get install netcdf-bin libnetcdf-dev doxygen graphviz wget gfortran \
        libjpeg-dev libz-dev openmpi-bin libopenmpi-dev cmake pnetcdf-bin libpnetcdf-dev
        
    - name: cmake build
      uses: ./.github/actions/parallelio_cmake
      with:
        parallelio_version: ${{ env.GITHUB_SHA }}
        enable_fortran: False
        enable_logging: True
        install_prefix: ${GITHUB_WORKSPACE}/parallelio
        with_mpiexec: mpiexec --oversubscribe
    - name: parallelio tests
      run: |
        pushd $GITHUB_WORKSPACE/build
        make tests VERBOSE=1
        ctest -VV
        popd

