name: cmake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CC: mpicc
      FC: mpifort
      CPPFLAGS: "-I/usr/include -I/usr/local/include -I/home/runner/pnetcdf/include"
      LDFLAGS: "-L/home/runner/pnetcdf/lib"
      LD_LIBRARY_PATH: "/home/runner/pnetcdf/lib"
      PNETCDF_VERSION: checkpoint.1.12.3
      FCFLAGS: "-fallow-argument-mismatch"
    steps:
    - uses: actions/checkout@v3
    - name: Installs
      run: |
        set -x
        #sudo gem install apt-spy2
        #sudo apt-spy2 check
        #sudo apt-spy2 fix --commit
        # after selecting a specific mirror, we need to run 'apt-get update'
        sudo apt-get update
        sudo apt-get install netcdf-bin libnetcdf-dev doxygen graphviz wget gfortran libjpeg-dev libz-dev openmpi-bin libopenmpi-dev cmake

    - name: cache-pnetcdf
      id: cache-pnetcdf
      uses: actions/cache@v3
      with:
        path: ~/pnetcdf
        key: pnetcdf-${{ runner.os }}-${{ env.PNETCDF_VERSION }}
    - name: Build PNetCDF
      if: steps.cache-pnetcdf.outputs.cache-hit != 'true'
      uses: ESCOMP/CDEPS/.github/actions/buildpnetcdf@e06246b560d3132170bb1a5443fa3d65dfbd2040
      with:
        pnetcdf_version: ${{ env.PNETCDF_VERSION }}
        install_prefix: $HOME/pnetcdf

    - name: cmake build
      run: |
        set -x
        mkdir build
        cd build
        cmake -Wno-dev -DNetCDF_C_LIBRARY=/usr/lib/x86_64-linux-gnu/libnetcdf.so \
        -DNetCDF_C_INCLUDE_DIR=/usr/include -DPnetCDF_PATH='/home/runner/pnetcdf' \
        -DPIO_ENABLE_FORTRAN=Off \
        -DPIO_ENABLE_LOGGING=On -DPIO_ENABLE_TIMING=Off  -DMPIEXEC_PREFLAGS="--oversubscribe" ..
        make VERBOSE=1
        make tests VERBOSE=1
        ctest -VV
