name: cmake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CC: mpicc
      FC: mpifort
      CPPFLAGS: "-I/usr/include -I/usr/local/include -I${GITHUB_WORKSPACE}/pnetcdf/include"
      LDFLAGS: "-L/usr/lib -L${GITHUB_WORKSPACE}/pnetcdf/lib "
      LD_LIBRARY_PATH: "/usr/lib:${GITHUB_WORKSPACE}/pnetcdf/lib"
      PNETCDF_VERSION: checkpoint.1.12.3
      FCFLAGS: "-fallow-argument-mismatch"
    steps:
    - uses: actions/checkout@v3
    - name: Installs
      run: |
        set -x
        sudo apt-get update
        sudo apt-get install netcdf-bin libnetcdf-dev doxygen graphviz wget gfortran libjpeg-dev libz-dev openmpi-bin libopenmpi-dev cmake

    - name: cache-pnetcdf
      id: cache-pnetcdf
      uses: actions/cache@v3
      with:
        path: ~/work/ParallelIO/ParallelIO/pnetcdf
        key: pnetcdf-${{ runner.os }}-${{ env.PNETCDF_VERSION }}
    - name: Build PNetCDF
      if: steps.cache-pnetcdf.outputs.cache-hit != 'true'
      uses: ./.github/actions/buildpnetcdf
      with:
        pnetcdf_version: ${{ env.PNETCDF_VERSION }}
        install_prefix: ${GITHUB_WORKSPACE}/pnetcdf
        enable_shared: False
    - name: prep step
      run: |
        export LDFLAGS="-L/usr/lib -lnetcdf -L${GITHUB_WORKSPACE}/pnetcdf/lib -lpnetcdf"

        
    - name: cmake build
      uses: ./.github/actions/parallelio_cmake
      with:
        parallelio_version: ${{ env.GITHUB_SHA }}
        with_pnetcdf: ${GITHUB_WORKSPACE}/pnetcdf
        with_netcdf: /usr
        enable_fortran: False
        enable_logging: True
        install_prefix: ${GITHUB_WORKSPACE}/parallelio
        with_mpiexec: mpiexec --oversubscribe
    - name: parallelio tests
      run: |
        pushd $GITHUB_WORKSPACE/build
        make tests VERBOSE=1
        ctest -VV
        popd

