Debugger entered--Lisp error: (void-variable DISTCHECK_CONFIGURE_FLAGS=)
  eval(DISTCHECK_CONFIGURE_FLAGS= nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
