name: netcdf_master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CC: mpicc
      FC: mpifort
      CPPFLAGS: "-I/usr/include -I/usr/local/include"
#      CFLAGS: "-std=c99  -fsanitize=address -fno-omit-frame-pointer -Werror"
#      FFLAGS: "-fsanitize=address -fno-omit-frame-pointer"
#      FCFLAGS: "-fsanitize=address -fno-omit-frame-pointer -Werror"

    steps:
    - uses: actions/checkout@v2
    - name: Installs
      run: |
        sudo apt-get install wget gfortran libjpeg-dev libz-dev openmpi-bin libopenmpi-dev 

    - name: pnetcdf build
      run: |
        wget https://parallel-netcdf.github.io/Release/pnetcdf-1.11.0.tar.gz 
        tar -xzvf pnetcdf-1.11.0.tar.gz
        ls -l
        pushd pnetcdf-1.11.0
        ./configure --prefix=/usr --enable-shared
        make
        sudo make install
        popd

    - name: HDF5 build
      run: |
        wget -o logfile https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.gz
        cat logfile
        tar -xzvf hdf5-1.10.6.tar.gz
        ls -l
        pushd hdf5-1.10.6
        ./configure --prefix=/usr --enable-parallel
        make
        sudo make install
        popd

    - name: netcdf build
      run: |
        git clone https://github.com/Unidata/netcdf-c.git
        cd netcdf-c
        autoreconf -i
        ./configure --prefix=/usr
        make
        sudo make install
        popd

    - name: netcdf-fortran build
      run: |
        git clone https://github.com/Unidata/netcdf-fortran.git
        cd netcdf-fortran
        autoreconf -i
        ./configure --prefix=/usr
        make
        sudo make install
        popd

    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
