# Author Jim Edwards
# The mpich image has a serial build of netcdf installed in /usr/local/serial
# and a parallel build of netcdf and pnetcdf in /usr/local/parallel
# we will first build and test a minimal pio using only netcdf serial build
# then we will do a complete build with the parallel versions
#
name: ParallelIO testing with ubuntu Dockerfile
on: [push]

jobs:
  build_mpich:
    runs-on: ubuntu-latest
    strategy:
#      fail-fast: false
      matrix:
        # 4.0.1 generates an error https://github.com/NCAR/ParallelIO/issues/1912
        mpich: [3.4.3, 4.0.1]
        # 1.10 needs to be a string or the trailing 0 is lost
        hdf5: ["1.10", "1.12"]
        netcdfc: [4.7.4, 4.8.1]
        netcdff: [4.5.4]
        pnetcdf: [1.12.3]
        integration: [OFF]
        # Integration needs fixed for netcdf 4.8.1 https://github.com/NCAR/ParallelIO/issues/1889
        # and fails container tests in mpich
        exclude:
          - netcdfc: 4.8.1
            integration: ON
        include:
          - hdf5: "1.10"
            hdf5m: 8
          - hdf5: "1.12"
            hdf5m: 1
    env:
      CC: mpicc
      FC: mpifort
      CPPFLAGS: "-I/usr/include -I/usr/local/serial/include "
      LDFLAGS: "-L/usr/local/serial/lib"
      LD_LIBRARY_PATH: "/usr/local/serial/lib"
      CMAKE_PREFIX_PATH: "build/CMake_Fortran_utils"
    container:
      image: jedwards4b/m${{ matrix.mpich }}h${{ matrix.hdf5 }}nc${{ matrix.netcdfc }}nf${{ matrix.netcdff }}p${{ matrix.pnetcdf }}
      options: --user 1001
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: checkout cmake_fortran_utils
      uses: actions/checkout@v3
      with:
        repository: CESM-Development/CMake_Fortran_utils
        path: build/CMake_Fortran_utils
    - name: checkout genf90
      uses: actions/checkout@v3
      with:
        repository: ParallelIO/genf90
        path: build/genf90
    - name: cmake (serial netcdf) build
      run: |
        cd build
        export PATH=/usr/local/parallel/bin:$PATH
        cmake -Wno-dev \
            -DGENF90_PATH=${GITHUB_WORKSPACE}/build/genf90 \
            -DNetCDF_PATH=/usr/local/serial \
            -DPIO_HDF5_LOGGING=On \
            -DPIO_ENABLE_FORTRAN=OFF \
            -DPIO_ENABLE_LOGGING=On \
            -DPIO_ENABLE_TIMING=Off \
            ..
            # Integration errors when using netcdf serial build: https://github.com/NCAR/ParallelIO/issues/1917
            #            -DPIO_ENABLE_NETCDF_INTEGRATION=${{ matrix.integration }} \
        make VERBOSE=1
        make tests VERBOSE=1
        ctest -VV
    - name: autotools (serial netcdf) build
      run: |
        set -x
        gcc --version
        autoreconf -i
        ./configure  
        # Integration errors when using netcdf serial build: https://github.com/NCAR/ParallelIO/issues/1917
        #        --enable-netcdf-integration=${{ matrix.integration }}
        make -j check

    - name: cmake (parallel netcdf + pnetcdf) build
      run: |
        cd build
        export PATH=/usr/local/parallel/bin:$PATH
        cmake -Wno-dev \
            -DGENF90_PATH=${GITHUB_WORKSPACE}/build/genf90 \
            -DNetCDF_PATH=/usr/local/parallel \
            -DPIO_HDF5_LOGGING=On \
            -DPIO_ENABLE_FORTRAN=ON \
            -DPIO_ENABLE_LOGGING=On \
            -DPIO_ENABLE_TIMING=Off \
            -DPIO_ENABLE_NETCDF_INTEGRATION=${{ matrix.integration }} \
            ..
        make VERBOSE=1
        make tests VERBOSE=1
        ctest -VV
    - name: autotools (parallel netcdf + pnetcdf) build
      run: |
        set -x
        gcc --version
        autoreconf -i
        LDFLAGS="-L/usr/local/parallel/lib "
        ./configure  --enable-fortran \
        --enable-netcdf-integration=${{ matrix.integration }}
        make -j check
