name: ubuntu_16

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    env:
      CC: mpicc
      FC: mpifort
      CPPFLAGS: "-I/usr/include -I/usr/local/include"
      CFLAGS: "-std=c99  -fsanitize=address -fno-omit-frame-pointer -Werror"
      FFLAGS: "-fsanitize=address -fno-omit-frame-pointer"
      FCFLAGS: "-fsanitize=address -fno-omit-frame-pointer -Werror"

    steps:
    # Use this GitHub Actions at least once in this workflow as soon as possible.
    - uses: technote-space/auto-cancel-redundant-job@v1
    - uses: actions/checkout@v2
    - name: Installs
      run: |
        sudo apt-get install netcdf-bin libnetcdf-dev doxygen graphviz wget gfortran libjpeg-dev libz-dev openmpi-bin libopenmpi-dev gcc

    - name: pnetcdf build
      run: |
        gcc --version
        wget https://parallel-netcdf.github.io/Release/parallel-netcdf-1.9.0.tar.gz
        tar -xzvf parallel-netcdf-1.9.0.tar.gz
        ls -l
        pushd parallel-netcdf-1.9.0
        ./configure --prefix=/usr --enable-shared
        make
        sudo make install
        popd
        
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

