name: Build with Spack
# Tests ParallelIO using Intel Compiler and IMPI library.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Installs
      run: |
        set -x
        sudo apt-get update 
        sudo apt-get install wget
        sudo apt-get install libjpeg-dev
        sudo apt-get install libz-dev
        sudo apt-get install gfortran

    - name: cache spack
      id: cache-spack
      uses: actions/cache@v3
      with:
        path: |
          ~/work/ParallelIO/ParallelIO/spack
          ~/.spack
        key: spack-${{ runner.os }}
    - name: Get Spack
      if: steps.cache-spack.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: spack/spack
        path: spack
        ref: v0.19.0
    - name: Prep spack
      run: |
        source $GITHUB_WORKSPACE/spack/share/spack/setup-env.sh
        spack compiler find
        spack dev-build -d $GITHUB_WORKSPACE parallelio@develop
        #    - name: Setup tmate session
#      if: ${{ failure() }}
#      uses: mxschmitt/action-tmate@v3
