#!/bin/bash
#
# PBS batch script to run an MPI application
#
#PBS -N test_z5            
#PBS -A NIOW0001        
#PBS -l walltime=00:30:00               
#PBS -q regular          
#PBS -j oe     
#PBS -M weile@ucar.edu
#PBS -l select=1:ncpus=4:mpiprocs=4                 

### setenv OMP_NUM_THREADS 1
### run the executable
### mkdir -p /glade/scratch/haiyingx/temp
### export TMPDIR=/glade/scratch/haiyingx/temp
### module load netcdf
### setenv LD_LIBRARY_PATH /usr/lib68":$LD_LIBRARY_PATH"
### echo $LD_LIBRARY_PATH
### setenv MPI_SHEPHERD true
### mpirun -n 4  ./testphdf5
mpiexec_mpt -n 4 ./test_z5_create_file >& tmp
#/glade/u/apps/ch/opt/arm-forge/19.1/gnu/8.3.0/bin/ddt  --connect -n 4 ./test_pioc_putget >& tmp
### ddt --connect -np 4  ./a.out
### mpiexec_mpt dplace -s 1 ./testphdf5 >& output.txt
### mpiexec_mpt  dplace -s 1  /glade/p/work/haiyingx/hdf5-1.10.2/testpar/.libs/t_filters_parallel  >& output.txt
### mpirun -n 1  /glade/p/work/haiyingx/hdf5-1.10.2-impi/testpar/.libs/t_filters_parallel  >& output.txt
### ddt --connect ./testphdf5 -v 7  
### ddt --connect -np 10   /glade/p/work/haiyingx/hdf5-1.10.2/testpar/.libs/t_filters_parallel -verbose high 
